name: keyword_scan

on:
  pull_request:
    branches:
      - main
    paths:
      - 'keywordscan/**'  
  push:
    branches:
      - main
    paths:
      - 'keywordscan/**'  

jobs:
  keyword-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Scan for keywords
        run: |
          
          if [ $(git grep -c "sysadmin" | wc -l) -gt 0 ]; then
              echo "Found the string '$SEARCH_STRING' in the repository."
          else
              echo "Did not find the string '$SEARCH_STRING' in the repository."
          fi
          
