name: keyword_scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  keyword-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Scan for keywords
        run: |
          SEARCH_STRING="sysadmin"
          if grep -rq "$SEARCH_STRING" .; then
              echo "Found the string '$SEARCH_STRING' in the repository."
          else
              echo "Did not find the string '$SEARCH_STRING' in the repository."
          fi
          
